FROM python:3.7.16-slim

WORKDIR /app

RUN pip install --upgrade pip && \
    pip install gym==0.25.2 \
                tensorflow==2.1.0 \
                keras-rl2 \
                numpy \
                pyglet \
                "protobuf==3.20.*" \
                pygame \
                jupyter
                